/* 
1) create a new pipeline called: challenge3
2) Add 3 parameters
    - Get input for our custom deployment name
    - Select which AZ to deploy to: EU-WEST-2A, EU-WEST-2B, EU-WEST-2C
    - Checkbox to confirm deployment
3) Check if it runs and works
*/


pipeline {
    agent any

    parameters {
        string(defaultValue: "", description: "Deployment name?", name: "deploymentName")
        choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "What AZ?", name: "azDeploy")
        booleanParam(defaultValue: false, description: "CONFIRM DEPLOYMENT?", name: "confirmDeploy")
    }

    stages {
        stage("Deploy"){
            steps {
                echo "String set to: ${deploymentName} \n"
                echo "Choice set to: ${azDeploy} \n"
                echo "Bool set to: ${confirmDeploy} \n"
            }
        }
    }
}