pipeline {
    agent any

    environment {
        def myString = "Hello World"
        def myNumber = 38
        def myBoolean = true
    }

    stages{
        stage("Demo") {
            steps {
                echo "myStrin: ${myString}"
                echo "myNumber: ${myNumber}"
                echo "myBoolean: ${myBoolean}"
            }
        }
    }
}